# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# This pipeline is meant to be run via the Buildkite API, and is
# only used for beta builds

agents:
  queue: "android"

steps:
  #################
  # Gradle Wrapper Validation
  #################
  - label: "Gradle Wrapper Validation"
    command: |
      .buildkite/commands/checkout-release-branch.sh "$RELEASE_VERSION"
      validate_gradle_wrapper
    plugins: [$CI_TOOLKIT]

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  #################
  # Lint
  #################
  - group: "🕵️ Lint"
    steps:

      - label: "🕵️ Lint WordPress"
        key: wplint
        command: |
          .buildkite/commands/checkout-release-branch.sh "$RELEASE_VERSION"
          .buildkite/commands/lint.sh wordpress
        plugins: [$CI_TOOLKIT]
        artifact_paths:
          - "**/build/reports/lint-results*.*"

      - label: "🕵️ Lint Jetpack"
        key: jplint
        command: |
          .buildkite/commands/checkout-release-branch.sh "$RELEASE_VERSION"
          .buildkite/commands/lint.sh jetpack
        plugins: [$CI_TOOLKIT]
        artifact_paths:
          - "**/build/reports/lint-results*.*"

  #################
  # Beta Builds
  #################
  - group: "🚀 Beta Builds"
    steps:

      - label: ":wordpress: :android: Beta Build"
        key: wpbuild
        command: |
          .buildkite/commands/checkout-release-branch.sh "$RELEASE_VERSION"
          .buildkite/commands/beta-build.sh wordpress
        depends_on: wplint
        plugins: [$CI_TOOLKIT]
        notify:
          - slack: "#build-and-ship"
        retry:
          manual:
            # If those jobs fail, one should always prefer re-triggering a new build from ReleaseV2 rather than retrying the individual job from Buildkite
            allowed: false
        artifact_paths:
          - "**/build/build.log"

      - label: ":jetpack: :android: Beta Build"
        key: jpbuild
        command: |
          .buildkite/commands/checkout-release-branch.sh "$RELEASE_VERSION"
          .buildkite/commands/beta-build.sh jetpack
        depends_on: jplint
        plugins: [$CI_TOOLKIT]
        notify:
          - slack: "#build-and-ship"
        retry:
          manual:
            # If those jobs fail, one should always prefer re-triggering a new build from ReleaseV2 rather than retrying the individual job from Buildkite
            allowed: false
        artifact_paths:
          - "**/build/build.log"

  #################
  # GitHub Release
  #################
  - label: ":github: Release"
    depends_on:
      - wpbuild
      - jpbuild
    command: |
      .buildkite/commands/checkout-release-branch.sh "$RELEASE_VERSION"
      .buildkite/commands/create-github-release.sh
    plugins: [$CI_TOOLKIT]
